### ISSUE TITLE
Diff vs thème Jekyll

### ISSUE THREAD

**Issue by pabois** [noesya/clermontauvergne-journal-degrowth#5]
- [x] Accueil à la place de home
- [x] lien "PDF" a disparu dans une page de volume (https://degrowthjournal-hugo.netlify.app/volumes/2021/degrowth-synthesized/)
- [x] issn a disparu dans la page du volume (mais est dans le footer)

### fiche d'un article 

- [x] la date a disparu
- [x] le lien pdf aussi
- [x] les authors n'ont plus (tous) leur preview ni leur lien en savoir plus

**Comment by sebousan** [comment]
* Lien pdf non présent dans le frontmatter md
* c'était une erreur, issn c'est pour un journal, pas pour un volume
* il manque de la bio pour les authors dans osuny

**Comment by sebousan** [comment]
Je ne comprends pas pourquoi la date ne s'affiche pas sur un article @arnaudlevy 

Sur IUT
* https://github.com/noesya/bordeauxmontaigne-iut/blob/main/content/posts/2021/2021-12-03-aide-sociale-de-l-universite-ex-fsdie.html
* https://github.com/noesya/osuny-hugo-theme/blob/main/layouts/posts/single.html#L23

Sur Degrowth
* https://github.com/noesya/clermontauvergne-journal-degrowth/blob/main/content/articles/2021/2021-09-08-counter-hegemonic-decision-premises-in-commons-based-peer-production-a-degrowth-case-study.html#L8
* https://github.com/noesya/osuny-hugo-theme/blob/main/layouts/articles/single.html#L88
